import { Link } from "react-router-dom";

// Generated by chatgpt
const NotFoundPage = () => {
  return (
    <div className="not-found-page">
      <h1>404</h1>
      <h2>Page Not Found</h2>
      <p>Sorry, the page you are looking for could not be found.</p>
      <Link to="/" className="main-link">Go to the home page</Link>
    </div>
  );
};

export default NotFoundPage;